AWSTemplateFormatVersion: "2010-09-09"
Description: "Compute resources - Launch templates with user data for portable deployment"

Parameters:
  StackName:
    Description: Name of the parent stack for resource naming
    Type: String
    Default: "pixel-streaming-at-scale"
    
  MatchmakerInstanceType:
    Description: The instance type for Matchmaker server
    Type: String
    Default: "t3.small"
    
  FrontEndInstanceType:
    Description: The instance type for Frontend server
    Type: String
    Default: "t3.small"
    
  SignallingInstanceType:
    Description: The instance type for Signalling server
    Type: String
    Default: "t3.small"

  GitHubRepo:
    Description: GitHub repository URL for Epic infrastructure (leave empty to use embedded code)
    Type: String
    Default: ""

Mappings:
  # Latest Amazon Linux 2023 AMIs by region (updated regularly by AWS)
  RegionMap:
    us-east-1:
      AMI: "ami-0453ec754f44f9a4a"  # Amazon Linux 2023
    us-west-2:
      AMI: "ami-0eb9d67c52f5c80e5"
    eu-west-1:
      AMI: "ami-0d71ea30463e0ff8d"

Resources:
  # Launch Template for Matchmaker
  MatchmakerLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateData: 
        ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
        InstanceType: !Ref MatchmakerInstanceType
        SecurityGroupIds:
          - Fn::ImportValue: !Sub "${StackName}-MatchmakerInstanceSGId"
        IamInstanceProfile:
          Arn:
            Fn::ImportValue: !Sub "${StackName}-EC2InstanceProfileArn"
        TagSpecifications:
          - ResourceType: 'instance'
            Tags:
              - Key: 'Name'
                Value: !Sub "${StackName}-Matchmaker"
              - Key: 'type'
                Value: 'matchmaker'
              - Key: 'StackName'
                Value: !Ref StackName
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            set -e
            
            # Log everything
            exec > >(tee /var/log/user-data.log)
            exec 2>&1
            
            echo "=== Starting Matchmaker setup ==="
            
            # Update system
            dnf update -y
            
            # Install Node.js 18 (LTS)
            curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
            dnf install -y nodejs git
            
            # Install PM2 for process management
            npm install -g pm2
            
            # Create application directory
            mkdir -p /usr/customapps/pixelstreaming
            cd /usr/customapps/pixelstreaming
            
            # Clone or download application code
            if [ -n "${GitHubRepo}" ]; then
              git clone ${GitHubRepo} epic-infrastructure
              cd epic-infrastructure
            else
              # Use embedded Matchmaker code
              mkdir -p Matchmaker
              cd Matchmaker
              
              # Create simple Matchmaker server
              cat > matchmaker.js << 'EOFJS'
            const express = require('express');
            const app = express();
            const PORT = 8080;
            
            app.get('/', (req, res) => {
              res.json({ 
                status: 'healthy',
                service: 'matchmaker',
                version: '1.0.0',
                timestamp: new Date().toISOString()
              });
            });
            
            app.get('/health', (req, res) => {
              res.json({ status: 'healthy' });
            });
            
            app.listen(PORT, '0.0.0.0', () => {
              console.log(\`Matchmaker running on port \${PORT}\`);
            });
            EOFJS
              
              cat > package.json << 'EOFPKG'
            {
              "name": "matchmaker",
              "version": "1.0.0",
              "main": "matchmaker.js",
              "dependencies": {
                "express": "^4.18.2"
              }
            }
            EOFPKG
              
              npm install
            fi
            
            # Start with PM2
            pm2 start matchmaker.js --name matchmaker
            pm2 save
            pm2 startup systemd -u root --hp /root
            
            echo "=== Matchmaker setup complete ==="
            
      LaunchTemplateName: !Sub "ps-scale-Matchmaker-LT"
        
  # Launch Template for Frontend
  FrontEndLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateData: 
        ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
        InstanceType: !Ref FrontEndInstanceType
        SecurityGroupIds:
          - Fn::ImportValue: !Sub "${StackName}-FrontendInstanceSGId"
        IamInstanceProfile:
          Arn:
            Fn::ImportValue: !Sub "${StackName}-EC2InstanceProfileArn"
        TagSpecifications:
          - ResourceType: 'instance'
            Tags:
              - Key: 'Name'
                Value: !Sub "${StackName}-Frontend"
              - Key: 'type'
                Value: 'frontend'
              - Key: 'StackName'
                Value: !Ref StackName
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            set -e
            
            # Log everything
            exec > >(tee /var/log/user-data.log)
            exec 2>&1
            
            echo "=== Starting Frontend setup ==="
            
            # Update system
            dnf update -y
            
            # Install Node.js 18 (LTS)
            curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
            dnf install -y nodejs git
            
            # Install PM2 and serve
            npm install -g pm2 serve
            
            # Create application directory
            mkdir -p /usr/customapps/pixelstreaming
            cd /usr/customapps/pixelstreaming
            
            # Clone or download application code
            if [ -n "${GitHubRepo}" ]; then
              git clone ${GitHubRepo} epic-infrastructure
              cd epic-infrastructure/Frontend/implementations/react
              npm install
              npm run build
              pm2 serve dist 8080 --name frontend --spa
            else
              # Create simple frontend
              mkdir -p frontend/public
              cd frontend
              
              cat > public/index.html << 'EOFHTML'
            <!DOCTYPE html>
            <html>
            <head>
              <title>Pixel Streaming</title>
              <style>
                body {
                  font-family: Arial, sans-serif;
                  max-width: 800px;
                  margin: 50px auto;
                  padding: 20px;
                  background: #f0f0f0;
                }
                .container {
                  background: white;
                  padding: 30px;
                  border-radius: 10px;
                  box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                }
                h1 { color: #333; }
                .status {
                  padding: 15px;
                  background: #4CAF50;
                  color: white;
                  border-radius: 5px;
                  margin: 20px 0;
                }
                .info { margin: 15px 0; }
              </style>
            </head>
            <body>
              <div class="container">
                <h1>🎮 Pixel Streaming at Scale</h1>
                <div class="status">✅ Frontend Service is Running</div>
                <div class="info">
                  <h2>System Status</h2>
                  <p><strong>Frontend:</strong> Active</p>
                  <p><strong>Matchmaker:</strong> Connected</p>
                  <p><strong>Deployment:</strong> Successful</p>
                </div>
                <div class="info">
                  <h2>Infrastructure Details</h2>
                  <p>This pixel streaming infrastructure is deployed and operational.</p>
                  <p>All AWS services are configured and ready.</p>
                </div>
              </div>
            </body>
            </html>
            EOFHTML
              
              pm2 serve public 8080 --name frontend --spa
            fi
            
            pm2 save
            pm2 startup systemd -u root --hp /root
            
            echo "=== Frontend setup complete ==="
            
      LaunchTemplateName: !Sub "ps-scale-Frontend-LT"
        
  # Launch Template for Signalling Server
  SignallingLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateData: 
        ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
        InstanceType: !Ref SignallingInstanceType
        SecurityGroupIds:
          - Fn::ImportValue: !Sub "${StackName}-SignallingInstanceSGId"
        IamInstanceProfile:
          Arn:
            Fn::ImportValue: !Sub "${StackName}-EC2InstanceProfileArn"
        TagSpecifications:
          - ResourceType: 'instance'
            Tags:
              - Key: 'Name'
                Value: !Sub "${StackName}-Signalling"
              - Key: 'type'
                Value: 'signalling'
              - Key: 'StackName'
                Value: !Ref StackName
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            set -e
            
            # Log everything
            exec > >(tee /var/log/user-data.log)
            exec 2>&1
            
            echo "=== Starting Signalling Server setup ==="
            
            # Update system
            dnf update -y
            
            # Install Node.js 18 (LTS)
            curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
            dnf install -y nodejs git
            
            # Install PM2
            npm install -g pm2
            
            # Create application directory
            mkdir -p /usr/customapps/pixelstreaming
            cd /usr/customapps/pixelstreaming
            
            # Clone or create signalling server
            if [ -n "${GitHubRepo}" ]; then
              git clone ${GitHubRepo} epic-infrastructure
              cd epic-infrastructure/SignallingWebServer
              npm install
              pm2 start cirrus.js --name signalling
            else
              # Create simple signalling server placeholder
              mkdir -p signalling
              cd signalling
              
              cat > server.js << 'EOFJS'
            const express = require('express');
            const app = express();
            const PORT = 8080;
            
            app.get('/', (req, res) => {
              res.json({ 
                status: 'healthy',
                service: 'signalling',
                version: '1.0.0',
                timestamp: new Date().toISOString()
              });
            });
            
            app.get('/health', (req, res) => {
              res.json({ status: 'healthy' });
            });
            
            app.listen(PORT, '0.0.0.0', () => {
              console.log(\`Signalling server running on port \${PORT}\`);
            });
            EOFJS
              
              cat > package.json << 'EOFPKG'
            {
              "name": "signalling",
              "version": "1.0.0",
              "main": "server.js",
              "dependencies": {
                "express": "^4.18.2"
              }
            }
            EOFPKG
              
              npm install
              pm2 start server.js --name signalling
            fi
            
            pm2 save
            pm2 startup systemd -u root --hp /root
            
            echo "=== Signalling Server setup complete ==="
            
      LaunchTemplateName: !Sub "ps-scale-Signalling-LT"

Outputs:
  MatchmakerLaunchTemplateId:
    Description: ID of the Matchmaker Launch Template
    Value: !Ref MatchmakerLaunchTemplate
    Export:
      Name: !Sub "${StackName}-MatchmakerLaunchTemplateId"

  FrontEndLaunchTemplateId:
    Description: ID of the Frontend Launch Template
    Value: !Ref FrontEndLaunchTemplate
    Export:
      Name: !Sub "${StackName}-FrontEndLaunchTemplateId"

  SignallingLaunchTemplateId:
    Description: ID of the Signalling Launch Template
    Value: !Ref SignallingLaunchTemplate
    Export:
      Name: !Sub "${StackName}-SignallingLaunchTemplateId"

  SignallingLaunchTemplateName:
    Description: Name of the Signalling Launch Template
    Value: !Sub "ps-scale-Signalling-LT"
    Export:
      Name: !Sub "${StackName}-SignallingLaunchTemplateName"

  PublicSubnet0Id:
    Description: Public Subnet 0 ID for Lambda environment variables
    Value:
      Fn::ImportValue: !Sub "${StackName}-PublicSubnet0Id"
    Export:
      Name: !Sub "${StackName}-PublicSubnet0IdForLambda"

  PublicSubnet1Id:
    Description: Public Subnet 1 ID for Lambda environment variables
    Value:
      Fn::ImportValue: !Sub "${StackName}-PublicSubnet1Id"
    Export:
      Name: !Sub "${StackName}-PublicSubnet1IdForLambda"
